#!/usr/bin/env python
#
# Copyright 2012-2013 SUSE Linux
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

import argparse
import glob
import os
import re
import subprocess
import sys


QUILT_PUSH_SUCCESS_RE = r"Now at patch pull-request-57.patch"
QUILT_PUSH_ERROR_RE = r"Patch .* does not apply (enforce with -f)$"
QUILT_FINISHED_RE = r"File series fully applied, ends at"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Refresh Patches")

    args = parser.parse_args()

    for specfile in glob.glob('./*.spec'):
        basename = specfile.rsplit('.spec')[0]

        output = subprocess.check_output(["quilt", "setup", specfile])
        match = re.search(r"Unpacking archive ({0}.*)$".format(basename), output)
        if not match:
            print("quilt setup failed")
            sys.exit(1)
        #NOTE(saschpe): Beautiful, I know:
        quilt_dir = match.group(1).rsplit(".tar")[0].rsplit(".zip")[0]

        src_dir = os.getcwd()
        os.chdir(quilt_dir)
        output = subprocess.check_output(["quilt", "push"])


        # Done with quilt, back to package sources
        os.chdir(src_dir)

   #quilt_setup()
   #quilt_push()

   #changes = create_changes()
   #if changes:
   #    update_changes_file(changes)
